spring:
  application:
    name: 'sneakershop'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/sneakershop'
    username: 'postgres'
    password: 'cityzens'
  security:
    user:
      name: root
      password: root
server:
  port: 8080


